// Complaint IDL (Interface Definition Language)
// This defines the structure and instructions for the Solana smart contract
// Generated by Anchor when you deploy the contract

export const COMPLAINT_IDL = {
  version: '0.1.0',
  name: 'complaint_contract',
  instructions: [
    {
      name: 'createComplaint',
      accounts: [
        {
          name: 'complaint',
          isMut: true,
          isSigner: true,
        },
        {
          name: 'author',
          isMut: true,
          isSigner: true,
        },
        {
          name: 'systemProgram',
          isMut: false,
          isSigner: false,
        },
      ],
      args: [
        {
          name: 'ipfsHash',
          type: 'string',
        },
        {
          name: 'category',
          type: 'string',
        },
        {
          name: 'location',
          type: 'string',
        },
      ],
    },
    {
      name: 'upvoteComplaint',
      accounts: [
        {
          name: 'complaint',
          isMut: true,
          isSigner: false,
        },
        {
          name: 'voter',
          isMut: false,
          isSigner: true,
        },
      ],
      args: [],
    },
    {
      name: 'updateStatus',
      accounts: [
        {
          name: 'complaint',
          isMut: true,
          isSigner: false,
        },
        {
          name: 'admin',
          isMut: false,
          isSigner: true,
        },
      ],
      args: [
        {
          name: 'newStatus',
          type: 'string',
        },
      ],
    },
  ],
  accounts: [
    {
      name: 'Complaint',
      fields: [
        {
          name: 'author',
          type: 'publicKey',
        },
        {
          name: 'ipfsHash',
          type: 'string',
        },
        {
          name: 'category',
          type: 'string',
        },
        {
          name: 'location',
          type: 'string',
        },
        {
          name: 'createdAt',
          type: 'i64',
        },
        {
          name: 'upvotes',
          type: 'u32',
        },
        {
          name: 'votedBy',
          type: {
            vec: 'publicKey',
          },
        },
        {
          name: 'status',
          type: 'string',
        },
        {
          name: 'admin',
          type: 'publicKey',
        },
      ],
    },
  ],
  events: [
    {
      name: 'ComplaintCreated',
      fields: [
        {
          name: 'complaintId',
          type: 'publicKey',
        },
        {
          name: 'author',
          type: 'publicKey',
        },
        {
          name: 'timestamp',
          type: 'i64',
        },
      ],
    },
    {
      name: 'ComplaintUpvoted',
      fields: [
        {
          name: 'complaintId',
          type: 'publicKey',
        },
        {
          name: 'voter',
          type: 'publicKey',
        },
        {
          name: 'totalUpvotes',
          type: 'u32',
        },
      ],
    },
    {
      name: 'StatusUpdated',
      fields: [
        {
          name: 'complaintId',
          type: 'publicKey',
        },
        {
          name: 'newStatus',
          type: 'string',
        },
      ],
    },
  ],
  errors: [
    {
      code: 6000,
      name: 'AlreadyVoted',
      msg: 'User has already voted on this complaint',
    },
    {
      code: 6001,
      name: 'UnauthorizedAdmin',
      msg: 'Only admin can update status',
    },
  ],
};
